version: '3.9'
services:
  newsfeed:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5588:8888"
    env_file:
      - ./.env
    container_name: trade_news_backend
    network_mode: host
    #    volumes:
    #       - ${PWD}:/code/
    #  db:
    #    image: postgres:12.0-alpine
    #    ports:
    #      - 5432:5432
    #    volumes:
    #      - postgres_data:/var/lib/postgresql/data/
    #    env_file:
    #      - ./.env
    #
    #volumes:
    #  postgres_data:
